#!/usr/bin/env python3
"""Generate deterministic source metadata for frozen MicroPython modules."""

from __future__ import annotations

import argparse
import os
import subprocess
from pathlib import Path
from typing import Optional

UNKNOWN_VALUE = "unknown"

# Environment switch used by release builds (see build_firmware.sh). When set, no
# git commands are run and every value is emitted as UNKNOWN_VALUE, so the frozen
# module is byte-identical whether the source came from a git checkout, a shallow
# clone, a fork, or a source archive without any .git metadata at all.
REPRODUCIBLE_ENV = "SPECTER_REPRODUCIBLE_BUILD"

# Optional explicit overrides. An empty value is treated as UNKNOWN_VALUE. These
# let a release process pin documented provenance constants without reintroducing
# any dependency on the local clone state.
REPOSITORY_ENV = "SPECTER_GIT_REPOSITORY"
BRANCH_ENV = "SPECTER_GIT_BRANCH"
COMMIT_ENV = "SPECTER_GIT_COMMIT"


def _run_git(args: list[str]) -> Optional[str]:
    try:
        result = subprocess.check_output(["git", *args], stderr=subprocess.DEVNULL)
    except (OSError, subprocess.CalledProcessError):
        return None
    return result.decode().strip() or None


def _env_override(name: str) -> Optional[str]:
    value = os.environ.get(name)
    if value is None:
        return None
    return value.strip() or UNKNOWN_VALUE


def _reproducible_build() -> bool:
    return os.environ.get(REPRODUCIBLE_ENV, "").strip() not in ("", "0", "false", "False")


def discover_repository() -> str:
    override = _env_override(REPOSITORY_ENV)
    if override is not None:
        return override
    # A clone remote is build-environment metadata, not source identity. Using
    # a canonical upstream URL would also misattribute fork-only commits to the
    # upstream repository, so do not embed a repository URL at all.
    return UNKNOWN_VALUE


def discover_branch() -> str:
    override = _env_override(BRANCH_ENV)
    if override is not None:
        return override
    # Branch/tag refs can differ for the same commit (branch checkout, detached
    # HEAD, shallow clone, etc.), so embedding them breaks reproducible builds.
    return UNKNOWN_VALUE


def discover_commit(reproducible: bool) -> str:
    override = _env_override(COMMIT_ENV)
    if override is not None:
        return override
    if reproducible:
        # The full object id is only present in a git checkout; a source archive
        # has no .git and would embed "unknown" instead. Release builds must not
        # depend on how the source was obtained, so drop it entirely.
        return UNKNOWN_VALUE
    # Dev builds embed the concrete revision. Use the full object id: git's
    # default abbreviated SHA length can vary with the objects present in a clone.
    commit = _run_git(["rev-parse", "HEAD"])
    if commit:
        return commit
    return UNKNOWN_VALUE


def build_content(repository: str, branch: str, commit: str) -> str:
    return (
        "# This file is auto-generated by tools/embed_git_info.py\n"
        "REPOSITORY = %r\n"
        "BRANCH = %r\n"
        "COMMIT = %r\n" % (repository, branch, commit)
    )


def write_git_info(path: Path, reproducible: bool) -> None:
    repository = discover_repository()
    branch = discover_branch()
    commit = discover_commit(reproducible)

    content = build_content(repository, branch, commit)

    path.parent.mkdir(parents=True, exist_ok=True)

    try:
        existing = path.read_text()
    except FileNotFoundError:
        existing = None

    if existing == content:
        return

    path.write_text(content)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "output",
        nargs="?",
        default="src/git_info.py",
        help="path to the generated git_info module",
    )
    parser.add_argument(
        "--reproducible",
        action="store_true",
        help=(
            "emit static values with no git lookups (also enabled by the "
            "%s environment variable)" % REPRODUCIBLE_ENV
        ),
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    reproducible = args.reproducible or _reproducible_build()
    write_git_info(Path(args.output), reproducible)


if __name__ == "__main__":
    main()
