#!/usr/bin/env python3
"""Generate deterministic source metadata for frozen MicroPython modules."""

from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path
from typing import Optional

UNKNOWN_VALUE = "unknown"


def _run_git(args: list[str]) -> Optional[str]:
    try:
        result = subprocess.check_output(["git", *args], stderr=subprocess.DEVNULL)
    except (OSError, subprocess.CalledProcessError):
        return None
    return result.decode().strip() or None


def _sanitize_remote_url(url: Optional[str]) -> str:
    """Strip credentials from a git remote URL before embedding.

    Origin URLs may contain tokens or passwords, e.g.
    https://<token>@github.com/org/repo.git or https://user:<password>@host/...
    These would end up frozen into firmware and shown on the About screen,
    so the userinfo component must never be embedded.

    Returns "unknown" for empty, malformed, or disallowed URLs.
    """
    if not url:
        return UNKNOWN_VALUE

    url = url.strip()

    # SCP-like SSH syntax (git@host:path, e.g. git@github.com:org/repo.git)
    # has no credential field, but the user part could still carry PII
    # (emails, internal usernames). Only the conventional "git" login used
    # by major hosting services is allowlisted; anything else without a
    # scheme (other users, local paths, junk strings) is rejected.
    if "://" not in url:
        if re.match(r"^git@[A-Za-z0-9._-]+(:[0-9]+)?:[^/\\].*$", url):
            return url
        return UNKNOWN_VALUE

    # Only allow safe protocols (reject file://, ftp://, etc.)
    # URL schemes are case-insensitive (RFC 3986), so match case-insensitively.
    allowed_schemes = ("https", "http", "ssh", "git")
    scheme_match = re.match(r"^([a-zA-Z][a-zA-Z0-9+.-]*)://", url)
    if scheme_match is None or scheme_match.group(1).lower() not in allowed_schemes:
        return UNKNOWN_VALUE

    # Strip userinfo: scheme://[user[:pass]@]host/path
    # [^@/]+ matches the userinfo component (no @ or / allowed inside)
    sanitized = re.sub(r"^([a-zA-Z][a-zA-Z0-9+.-]*://)[^@/]+@", r"\1", url)

    # Safety net: if after stripping we still have an @ in the netloc,
    # something is malformed (e.g. multiple @s). Fail closed to unknown.
    try:
        netloc = sanitized.split("://", 1)[1].split("/", 1)[0]
        if "@" in netloc:
            return UNKNOWN_VALUE
    except (IndexError, AttributeError):
        return UNKNOWN_VALUE

    return sanitized


def discover_repository() -> str:
    repo = _run_git(["config", "--get", "remote.origin.url"])
    if repo:
        return _sanitize_remote_url(repo)
    return UNKNOWN_VALUE


def discover_branch() -> str:
    branch = _run_git(["rev-parse", "--abbrev-ref", "HEAD"])
    if branch and branch != "HEAD":
        return branch
    describe = _run_git(["describe", "--all"])
    return describe or UNKNOWN_VALUE


def discover_commit() -> str:
    # Use the full object id: git's default abbreviated SHA length can vary with
    # the objects present in a clone.
    commit = _run_git(["rev-parse", "HEAD"])
    if commit:
        return commit
    return UNKNOWN_VALUE


def build_content(repository: str, branch: str, commit: str) -> str:
    return (
        "# This file is auto-generated by tools/embed_git_info.py\n"
        "REPOSITORY = %r\n"
        "BRANCH = %r\n"
        "COMMIT = %r\n" % (repository, branch, commit)
    )


def write_git_info(path: Path, reproducible: bool) -> None:
    if reproducible:
        repository = branch = commit = UNKNOWN_VALUE
    else:
        repository = discover_repository()
        branch = discover_branch()
        commit = discover_commit()

    content = build_content(repository, branch, commit)

    path.parent.mkdir(parents=True, exist_ok=True)

    try:
        existing = path.read_text()
    except FileNotFoundError:
        existing = None

    if existing == content:
        return

    path.write_text(content)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "output",
        nargs="?",
        default="src/git_info.py",
        help="path to the generated git_info module",
    )
    parser.add_argument(
        "--reproducible",
        action="store_true",
        help="emit static values with no git lookups",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    write_git_info(Path(args.output), args.reproducible)


if __name__ == "__main__":
    main()
